from PyQt5 import QtCore, QtGui, QtWidgets


exclude_time = []
rec_s = []
rec_e = []
rec = []


class Ui_Weekly_Stats_Application(object):

    def __init__(self):
        self.exclude_time = exclude_time
        self.rec_s = rec_s
        self.rec_e = rec_e
        self.rec = rec

    def setupUi(self, Weekly_Stats_Application):
        Weekly_Stats_Application.setObjectName("Weekly_Stats_Application")
        Weekly_Stats_Application.resize(1042, 312)
        Weekly_Stats_Application.setToolTipDuration(-5)
        self.gridLayoutWidget = QtWidgets.QWidget(Weekly_Stats_Application)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(480, 10, 551, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Week_Selection = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Week_Selection.setContentsMargins(0, 0, 0, 0)
        self.Week_Selection.setObjectName("Week_Selection")
        self.week_end = QtWidgets.QDateEdit(self.gridLayoutWidget)
        # Setting the date to today's date
        self.week_end.setDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime(23, 59, 59)))
        self.week_end.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.week_end.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.week_end.setCalendarPopup(True)
        self.week_end.setDate(QtCore.QDate.currentDate())
        self.week_end.setObjectName("week_end")
        self.Week_Selection.addWidget(self.week_end, 1, 1, 1, 1)
        self.week_end_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.week_end_label.setObjectName("week_end_label")
        self.Week_Selection.addWidget(self.week_end_label, 1, 0, 1, 1)
        self.week_start = QtWidgets.QDateEdit(self.gridLayoutWidget)
        # Setting the date to today's date
        self.week_start.setDateTime(QtCore.QDateTime(QtCore.QDate.currentDate(), QtCore.QTime(0, 0, 0)))
        self.week_start.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2050, 12, 31), QtCore.QTime(23, 59, 59)))
        self.week_start.setMaximumDate(QtCore.QDate(2050, 12, 31))
        self.week_start.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.week_start.setCalendarPopup(True)
        self.week_start.setDate(QtCore.QDate.currentDate())
        self.week_start.setObjectName("week_start")
        self.Week_Selection.addWidget(self.week_start, 0, 1, 1, 1)
        self.ok_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.ok_btn.setObjectName("ok_btn")
        self.Week_Selection.addWidget(self.ok_btn, 2, 1, 1, 1)
        self.week_start_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.week_start_label.setObjectName("week_start_label")
        self.Week_Selection.addWidget(self.week_start_label, 0, 0, 1, 1)
        self.ok_btn_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.ok_btn_label.setObjectName("ok_btn_label")
        self.Week_Selection.addWidget(self.ok_btn_label, 2, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(Weekly_Stats_Application)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 120, 1021, 185))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.Exclusion_Dates = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.Exclusion_Dates.setContentsMargins(0, 0, 0, 0)
        self.Exclusion_Dates.setObjectName("Exclusion_Dates")
        self.sun_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sun_label.setFont(font)
        self.sun_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sun_label.setObjectName("sun_label")
        self.Exclusion_Dates.addWidget(self.sun_label, 1, 0, 1, 1)
        self.get_data_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.get_data_btn.setObjectName("get_data_btn")
        self.Exclusion_Dates.addWidget(self.get_data_btn, 7, 5, 1, 2)
        self.save_exc_dates_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.save_exc_dates_btn.setObjectName("save_exc_dates_btn")
        self.Exclusion_Dates.addWidget(self.save_exc_dates_btn, 6, 5, 1, 2)
        self.thur_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.thur_label.setFont(font)
        self.thur_label.setAlignment(QtCore.Qt.AlignCenter)
        self.thur_label.setObjectName("thur_label")
        self.Exclusion_Dates.addWidget(self.thur_label, 1, 4, 1, 1)
        self.sat_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sat_label.setFont(font)
        self.sat_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sat_label.setObjectName("sat_label")
        self.Exclusion_Dates.addWidget(self.sat_label, 1, 6, 1, 1)
        self.fri_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fri_label.setFont(font)
        self.fri_label.setAlignment(QtCore.Qt.AlignCenter)
        self.fri_label.setObjectName("fri_label")
        self.Exclusion_Dates.addWidget(self.fri_label, 1, 5, 1, 1)
        self.mon_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.mon_label.setFont(font)
        self.mon_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mon_label.setObjectName("mon_label")
        self.Exclusion_Dates.addWidget(self.mon_label, 1, 1, 1, 1)
        self.tues_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tues_label.setFont(font)
        self.tues_label.setAlignment(QtCore.Qt.AlignCenter)
        self.tues_label.setObjectName("tues_label")
        self.Exclusion_Dates.addWidget(self.tues_label, 1, 2, 1, 1)
        self.wed_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.wed_label.setFont(font)
        self.wed_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wed_label.setObjectName("wed_label")
        self.Exclusion_Dates.addWidget(self.wed_label, 1, 3, 1, 1)
        self.sun_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sun_1st_btn.setCheckable(True)
        self.sun_1st_btn.setObjectName("sun_1st_btn")
        self.Exclusion_Dates_btns = QtWidgets.QButtonGroup(Weekly_Stats_Application)
        self.Exclusion_Dates_btns.setObjectName("Exclusion_Dates_btns")
        self.Exclusion_Dates_btns.setExclusive(False)
        self.Exclusion_Dates_btns.addButton(self.sun_1st_btn)
        self.Exclusion_Dates.addWidget(self.sun_1st_btn, 3, 0, 1, 1)
        self.mon_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.mon_1st_btn.setCheckable(True)
        self.mon_1st_btn.setObjectName("mon_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.mon_1st_btn)
        self.Exclusion_Dates.addWidget(self.mon_1st_btn, 3, 1, 1, 1)
        self.tues_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.tues_1st_btn.setCheckable(True)
        self.tues_1st_btn.setObjectName("tues_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.tues_1st_btn)
        self.Exclusion_Dates.addWidget(self.tues_1st_btn, 3, 2, 1, 1)
        self.sat_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sat_1st_btn.setCheckable(True)
        self.sat_1st_btn.setObjectName("sat_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.sat_1st_btn)
        self.Exclusion_Dates.addWidget(self.sat_1st_btn, 3, 6, 1, 1)
        self.fri_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fri_1st_btn.setCheckable(True)
        self.fri_1st_btn.setObjectName("fri_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.fri_1st_btn)
        self.Exclusion_Dates.addWidget(self.fri_1st_btn, 3, 5, 1, 1)
        self.thur_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.thur_1st_btn.setCheckable(True)
        self.thur_1st_btn.setObjectName("thur_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.thur_1st_btn)
        self.Exclusion_Dates.addWidget(self.thur_1st_btn, 3, 4, 1, 1)
        self.wed_1st_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.wed_1st_btn.setCheckable(True)
        self.wed_1st_btn.setObjectName("wed_1st_btn")
        self.Exclusion_Dates_btns.addButton(self.wed_1st_btn)
        self.Exclusion_Dates.addWidget(self.wed_1st_btn, 3, 3, 1, 1)
        self.wed_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.wed_2nd_btn.setCheckable(True)
        self.wed_2nd_btn.setObjectName("wed_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.wed_2nd_btn)
        self.Exclusion_Dates.addWidget(self.wed_2nd_btn, 4, 3, 1, 1)
        self.tues_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.tues_2nd_btn.setCheckable(True)
        self.tues_2nd_btn.setObjectName("tues_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.tues_2nd_btn)
        self.Exclusion_Dates.addWidget(self.tues_2nd_btn, 4, 2, 1, 1)
        self.tues_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.tues_3rd_btn.setCheckable(True)
        self.tues_3rd_btn.setObjectName("tues_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.tues_3rd_btn)
        self.Exclusion_Dates.addWidget(self.tues_3rd_btn, 5, 2, 1, 1)
        self.mon_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.mon_3rd_btn.setCheckable(True)
        self.mon_3rd_btn.setObjectName("mon_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.mon_3rd_btn)
        self.Exclusion_Dates.addWidget(self.mon_3rd_btn, 5, 1, 1, 1)
        self.mon_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.mon_2nd_btn.setCheckable(True)
        self.mon_2nd_btn.setObjectName("mon_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.mon_2nd_btn)
        self.Exclusion_Dates.addWidget(self.mon_2nd_btn, 4, 1, 1, 1)
        self.sun_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sun_2nd_btn.setCheckable(True)
        self.sun_2nd_btn.setObjectName("sun_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.sun_2nd_btn)
        self.Exclusion_Dates.addWidget(self.sun_2nd_btn, 4, 0, 1, 1)
        self.sun_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sun_3rd_btn.setCheckable(True)
        self.sun_3rd_btn.setObjectName("sun_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.sun_3rd_btn)
        self.Exclusion_Dates.addWidget(self.sun_3rd_btn, 5, 0, 1, 1)
        self.fri_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fri_2nd_btn.setCheckable(True)
        self.fri_2nd_btn.setObjectName("fri_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.fri_2nd_btn)
        self.Exclusion_Dates.addWidget(self.fri_2nd_btn, 4, 5, 1, 1)
        self.sat_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sat_2nd_btn.setCheckable(True)
        self.sat_2nd_btn.setObjectName("sat_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.sat_2nd_btn)
        self.Exclusion_Dates.addWidget(self.sat_2nd_btn, 4, 6, 1, 1)
        self.fri_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.fri_3rd_btn.setCheckable(True)
        self.fri_3rd_btn.setObjectName("fri_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.fri_3rd_btn)
        self.Exclusion_Dates.addWidget(self.fri_3rd_btn, 5, 5, 1, 1)
        self.sat_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.sat_3rd_btn.setCheckable(True)
        self.sat_3rd_btn.setObjectName("sat_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.sat_3rd_btn)
        self.Exclusion_Dates.addWidget(self.sat_3rd_btn, 5, 6, 1, 1)
        self.wed_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.wed_3rd_btn.setCheckable(True)
        self.wed_3rd_btn.setObjectName("wed_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.wed_3rd_btn)
        self.Exclusion_Dates.addWidget(self.wed_3rd_btn, 5, 3, 1, 1)
        self.thur_2nd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.thur_2nd_btn.setCheckable(True)
        self.thur_2nd_btn.setObjectName("thur_2nd_btn")
        self.Exclusion_Dates_btns.addButton(self.thur_2nd_btn)
        self.Exclusion_Dates.addWidget(self.thur_2nd_btn, 4, 4, 1, 1)
        self.thur_3rd_btn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.thur_3rd_btn.setCheckable(True)
        self.thur_3rd_btn.setObjectName("thur_3rd_btn")
        self.Exclusion_Dates_btns.addButton(self.thur_3rd_btn)
        self.Exclusion_Dates.addWidget(self.thur_3rd_btn, 5, 4, 1, 1)
        self.desc_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.desc_label.setFont(font)
        self.desc_label.setAlignment(QtCore.Qt.AlignCenter)
        self.desc_label.setObjectName("desc_label")
        self.Exclusion_Dates.addWidget(self.desc_label, 0, 0, 1, 7)
        self.save_exc_dates_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.save_exc_dates_label.setObjectName("save_exc_dates_label")
        self.Exclusion_Dates.addWidget(self.save_exc_dates_label, 6, 3, 1, 2)
        self.get_data_label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.get_data_label.setObjectName("get_data_label")
        self.Exclusion_Dates.addWidget(self.get_data_label, 7, 3, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(Weekly_Stats_Application)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 461, 101))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Weekly_Stats_Application)
        QtCore.QMetaObject.connectSlotsByName(Weekly_Stats_Application)

        self.ok_btn.clicked.connect(self.weekSelection)

    def retranslateUi(self, Weekly_Stats_Application):
        _translate = QtCore.QCoreApplication.translate
        Weekly_Stats_Application.setWindowTitle(_translate("Weekly_Stats_Application", "Weekly_Stats_Application"))
        self.week_end_label.setText(_translate("Weekly_Stats_Application", "Week End"))
        self.ok_btn.setText(_translate("Weekly_Stats_Application", "OK"))
        self.week_start_label.setText(_translate("Weekly_Stats_Application", "Week Start"))
        self.ok_btn_label.setText(_translate("Weekly_Stats_Application", "Press OK to use selected dates"))
        self.sun_label.setText(_translate("Weekly_Stats_Application", "Sun"))
        self.get_data_btn.setText(_translate("Weekly_Stats_Application", "Get Data"))
        self.save_exc_dates_btn.setText(_translate("Weekly_Stats_Application", "Save Exclusion Dates"))
        self.thur_label.setText(_translate("Weekly_Stats_Application", "Thur"))
        self.sat_label.setText(_translate("Weekly_Stats_Application", "Sat"))
        self.fri_label.setText(_translate("Weekly_Stats_Application", "Fri"))
        self.mon_label.setText(_translate("Weekly_Stats_Application", "Mon"))
        self.tues_label.setText(_translate("Weekly_Stats_Application", "Tues"))
        self.wed_label.setText(_translate("Weekly_Stats_Application", "Wed"))
        self.sun_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.mon_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.tues_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.sat_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.fri_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.thur_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.wed_1st_btn.setText(_translate("Weekly_Stats_Application", "00:00"))
        self.wed_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.tues_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.tues_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.mon_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.mon_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.sun_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.sun_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.fri_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.sat_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.fri_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.sat_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.wed_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.thur_2nd_btn.setText(_translate("Weekly_Stats_Application", "08:00"))
        self.thur_3rd_btn.setText(_translate("Weekly_Stats_Application", "16:00"))
        self.desc_label.setText(_translate("Weekly_Stats_Application", "Select shifts to be excluded from the above week, ie Maintenance or Development"))
        self.save_exc_dates_label.setText(_translate("Weekly_Stats_Application", "Press this button to have the excluded dates saved"))
        self.get_data_label.setText(_translate("Weekly_Stats_Application", "Press this button to get trip data for week"))
        self.textBrowser.setHtml(_translate("Weekly_Stats_Application", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">To use this application first select the date the week started on, then select the date the week ended on. Hit the OK button. Select all shifts that you want excluded from the week. These can be maintenance or development shifts. Select all that apply to that week then hit the Save Exclusion Dates button, that will allow the script to save these dates to be excluded. Once you are satisfied with everything, hit the Get Data button to get the trip data for the week.</p></body></html>"))

    def weekSelection(self):
        print(self.week_start)
        print(self.week_end)

        # url_archiver = 'http://vm-archiver-02.clsi.ca:17668/retrieval/ui/viewer/archViewer.html?pv=PCT1402-01:mA:fbk&from={}T00:00:00&to={}T23:59:59&binSize=30' \
            # .format(sunday.replace(',', '-'), saturday.replace(',', '-'))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Weekly_Stats_Application = QtWidgets.QWidget()
    ui = Ui_Weekly_Stats_Application()
    ui.setupUi(Weekly_Stats_Application)
    Weekly_Stats_Application.show()
    sys.exit(app.exec_())